### ISSUE TITLE
Change Soysuper.com logo

### ISSUE THREAD

**Issue by meis** [Act-Conferences/barcelona2016#18]
As a sponsor, Soysuper requested to change the logo we have in the front page with a new want including the '.com'

**Comment by diegok** [comment]
I will add this issue to the #47 list of sponsors if I got the image (and probably implemente it myself)

**Comment by diegok** [comment]
Ok, por fin lo he encontrado:

![logo-soysuper](https://cloud.githubusercontent.com/assets/50365/19429942/8bef2964-9452-11e6-8cde-1eba7f1b0a4a.png)
