### ISSUE TITLE
Style talks pages

### ISSUE THREAD

**Issue by meis** [Act-Conferences/barcelona2016#19]
- [ ] Style talks page (/talks)
- [ ] Style talk page (/talk)
- [x] See if we can add a widget with the approved talks at the front page.
- [ ] Discuss if we want/need the star/favorite/attending mechanism. This also applies to 'my schedule' page.

Personally, I think all the 'attendance' system is overkill for a one day, two track conference. I'm not sure if everyone understands what it means or adds value for anyone.  Maybe just with smart copy we can make it worth but I'm concerned that most of the time it'll just be an empty space on the talk page and weird checkboxes on the talk list.

This work should be done before accepting the first talk (/cc @alexm)

**Comment by jluis** [comment]
I've put my talk (on production) and I think that the 2 last points should get more attention that the first two
