### ISSUE TITLE
Organize opening talk

### ISSUE THREAD

**Issue by meis** [Act-Conferences/barcelona2016#35]
This includes:
- Decide who will give the opening talk.
- Decide the content of the talk

We still have time to decide that but I'm opening the ticket as a brainstorm wall. Please, add your ideas in the comments.

**Comment by meis** [comment]
Things I think we should include:
- Wifi password
- Warm welcome
- What's Barcelona.pm?
- Sponsors short speech (if they want)
- Explaining lightning talks
- Where is the schedule? (just in case)

**Comment by aferrer** [comment]
- Venue boundaries (attendees shouldn't access the working area).

**Comment by meis** [comment]
- Map of restaurants
- twitter hashtag

**Comment by aferrer** [comment]
Created "BCNPW2016 - Opening" Google Presentation in shared folder in Google Drive.

**Comment by aferrer** [comment]
Created "BCNPW2016 - Closing" Google Presentation in shared folder in Google Drive.
