### ISSUE TITLE
Lightning talks

### ISSUE THREAD

**Issue by meis** [Act-Conferences/barcelona2016#36]
We need:
- Short text to add to 'submit a talk' page and banner. This should encourage users to submit a lightning talk if they don't feel strong enough for a longer talk. Should probably link to the next section for a full information.
- Text to add to the 'Lightning talks' abstract talk. This will explain the mechanism a user should follow to submit a talk and how the lightning talks will work.
- When all this is published, maybe it's worth a marketing action.

**Comment by jluis** [comment]
I've been looking at it  and I working with this  texts:
http://www.perl.com/pub/2004/07/30/lightningtalk.html
https://www.software.ac.uk/home/cw11/giving-good-lightning-talk
http://perl.plover.com/lt/lightning-talks.html

for the short line I like :
"Get to your point early on; don't leave it to the end. remember, the audience is on your side!"
